### ISSUE TITLE
[feature]グループ作成機能の実装

### ISSUE THREAD

**Issue by KeitaOsaki** [Funcy-ICT/Funcy_Portfolio_Backend#104]
## 機能概要
- organization機能のグループ作成機能を実装する
## Taskリスト
- テーブル作成
- POST処理の実装
## Doneの定義
- POSTを実行することでグループが作成され一意のIDが割り振られている
## 参考リンク
データについて
- https://github.com/orgs/Funcy-ICT/discussions/16
## 留意事項
- 
## 検討事項
-

**Comment by KeitaOsaki** [comment]
以下、例
```
    CreateGroupRequest:
      properties:
        name:
          type: string
          description: グループ名
        description:
          type: string
          description: グループ名
        leader_email:
          type: string
          description: 代表者メールアドレス
        icon:
          type: string
          description: グループアイコン
```
